spring:
  profiles:
    active: local

boredApiBaseUrl: "https://www.boredapi.com"
---
spring:
  config:
    activate:
      on-profile:
        -local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

boredApiBaseUrl: "https://www.boredapi.com"

---
spring:
  config:
    activate:
      on-profile: non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

boredApiBaseUrl: "https://www.boredapi.com"